### ISSUE TITLE
Possible touchscreen

### ISSUE THREAD

**Issue by Freddson** [olm3ca/PixelbookOSX#1]
Touchscreen is possible in macOS using VoodooI2C, you'd need to use an additional SSDT, SSDT-GPIO.
The normal touchscreen type would be HID, so you'd need to use the VoodooI2C.kext and VoodooI2CHID.kext

**Comment by olm3ca** [comment]
Thanks! I'll try it as soon as accelerated graphics are working.

**Comment by Freddson** [comment]
No problem, good luck!

**Comment by olm3ca** [comment]
Touchscreen works! Ha. That's amazing. I had no idea... It's definitely helpful right now as the trackpad still doesn't respond. Thanks again!

**Comment by Freddson** [comment]
No problem!
