### ISSUE TITLE
External monitor not always detected

### ISSUE THREAD

**Issue by craigbeat** [olm3ca/PixelbookOSX#10]
When connecting to an external monitor, it is not detected, even when going into 'Displays' -> 'Detect' (hold command to make the button appear).
If I leave the monitor connected and wait for the computer to sleep, if I wake the device, 50% of the time, the external monitor will work as expected.

**Comment by olm3ca** [comment]
Yes, unfortunately this is true. Using Clover I could get the external monitor to work. I don't recommend using Clover, however.
