### ISSUE TITLE
Installing Mojave in MrChromebox 4.14 firmware

### ISSUE THREAD

**Issue by dd2090** [olm3ca/PixelbookOSX#13]
Good Morning!
I had several problems and found it impossible to install mojave after updating MrChromebox (apparently it worked until version 4.12). But after that it didn't work anymore. In pixelbook with mrchromebox 4.14 it always crashes in 2 minutes before the installation finishes in the first step of it and does not appear to continue the installation.

A solution that is not so simple:

1) I took the mojave 14.0 version in iso and installed it on an ssd in a windows virtual machine (I only did the first step of the installation - which crashes on the pixelbook)

2) I did not continue the installation by the virtual machine and put the external ssd in the pixelbook. I restarted the installation on the chromebook with a pendrive with mojave 14.1 and it crashed again in the first step with 2 minutes. However, when restarted appears to continue the second step of the installation.

3) Finally, I made a copy of the system using acronis 2020 (copying sector by sector) and copied it to the internal SSD. There working perfectly with dualbool with windows. (installed windows after mojave)

Note: I believe that installing in the virtual machine creates the recovery and boot partition that for some reason in the new version on mrchromebook is not creating. I haven't tried it with mojave version 14.6, but it might work. if anyone can let me know

**Comment by olm3ca** [comment]
Hi, sorry for not responding a while back. Glad you found a solution, and since this was posted, MrChromebox has updated the firmware a few times.
