### ISSUE TITLE
cannot boot into installation

### ISSUE THREAD

**Issue by Heroeshigh** [olm3ca/PixelbookOSX#20]
well, after all; I can't boot into the installation while using the config.plist like what you tell.
may can you trans me a proper one?
Or just like before, up the EFI folder you made?

**Comment by meghan06** [comment]
Upload your EFI.

**Comment by Heroeshigh** [comment]
it turns out that i'm working with a sumsung nvme 512 device;
and with your latest post it also cannt boot;and efi with oc-log uploaded.
[opencore-2023-02-27-212630.txt](https://github.com/olm3ca/PixelbookOSX/files/10836434/opencore-2023-02-27-212630.txt)
[EFI.zip](https://github.com/olm3ca/PixelbookOSX/files/10836440/EFI.zip)

**Comment by meghan06** [comment]
1.) You are supposed to have 2 kexts for USBToolBox. You need UTBMap.kext, and USBToolBox.kext. 
https://github.com/USBToolBox/kext/releases/tag/1.1.1
2.) Try booting without `SSDT-XOSI`.  Remove it and it's corresponding patch it makes no change. 
3.) Add `NVMEfix.kext`
4.) Remove `PciRoot(0x0)/Pci(0x1b,0x0)` under `DeviceProperties`
5.) Change your SMBIOS from `iMac18,1` to `MacBookAir8,1`. **This might be why you can't boot.**

If you get lucky, it might work after adding the changes above but understand there might never be support for your internal NVME drive. They just do not play well with macOS. 

Good job on the EFI though, it is probably one of the better/cleaner ones I've seen.

**Comment by olm3ca** [comment]
@meghan06 I thought USB Map isn't needed on Coreboot?

**Comment by Heroeshigh** [comment]
Changed but nothing change/
Changed my config.plist, it made something right I guess. Because after that I get a empty OC-log, but it also cannt boot or it got in boot loops. 
And changed into Mojave got the same situation(with config.plist fixed)
[config.plist.txt](https://github.com/olm3ca/PixelbookOSX/files/10839131/config.plist.txt)
how we do before? I remember that I made it with Mojave long time ago.

**Comment by Heroeshigh** [comment]
Changed but nothing change/
Changed my config.plist, it made something right I guess. Because after that I get a empty OC-log, but it also cannt boot or it got in boot loops. 
And changed into Mojave got the same situation(with config.plist fixed)
[config.plist.txt](https://github.com/olm3ca/PixelbookOSX/files/10839131/config.plist.txt)
how we do before? I remember that I made it with Mojave long time ago.

**Comment by meghan06** [comment]
> @meghan06 I thought USB Map isn't needed on Coreboot?

It isn't, but still recommended since it's what you should be doing anyway. 

@Heroeshigh try installing macOS Mojave to an external USB drive/ USB Disk. If you manage to boot successfully there, then it's an SSD issue.

**Comment by Heroeshigh** [comment]
@meghan06 I will try it if I get a spare ssd drive/disk. And I'm wondering why it effects, because I even cannt loading into the Apple logo,will the loading process detect SSD? if there nothing supported then it stuck in boot-loop?

**Comment by meghan06** [comment]
It has do to with your internal NVME's TRIM, it does not play well with macOS for some reason.

**Comment by olm3ca** [comment]
@Heroeshigh if it helps you, this is the last config.plist I was using on a 512GB NVMe Pixelbook on Mojave which can serve as reference. I've removed serials so you have to add them before trying to boot Mojave. 
[config.plist.txt](https://github.com/olm3ca/PixelbookOSX/files/10847874/config.plist.txt)

**Comment by meghan06** [comment]
@Heroeshigh If you still have issues, try setting `ApfsTrimTimeout` to `4294967295`. It **will** cause boot times to slow _**significantly**_ , i.e by minutes but it will probably work.

**Comment by Heroeshigh** [comment]
@olm3ca This config.plist works well, with it I can load into the recovery GUI, but there is no wifi support, and I'm trying to do a full installation without internet. Wishing good news.
@meghan06 Just like what I said above, I'll try it later.

**Comment by Heroeshigh** [comment]
@meghan06 I tried set ApfsTrimTimeout to 4294967295; It also went to boot-loop;
and I tried make a full installation with @olm3ca 's config.plist and it turn to this
![macos-big-sur-startup-screen-prohibitory-sign](https://user-images.githubusercontent.com/46957842/222037636-65e24013-1e15-4f71-9d5e-e0604fd531a1.jpg)

**Comment by meghan06** [comment]
What macOS version?

`XHCIPortLimit` -> False
Map your USB. If that still happens, reverse and remove your USB maps

**Comment by meghan06** [comment]
> there is no wifi support

Are you using AirportItlwm? It is version dependent so macOS 12's variant wont work on macOS 10.14.

**Comment by Heroeshigh** [comment]
Fianlly I did it. With @olm3ca config.plist and made a full installation. The forbidden page is caused by the USB port, left port is USB3.0 and I changed to USB2.0 port on the right. And everything works good but audio and trackpad.
<img width="585" alt="Screen Shot 2023-03-01 at 3 33 31 PM" src="https://user-images.githubusercontent.com/46957842/222073772-8ef3033c-0052-46b2-871f-66fb566d42c4.png">
<img width="868" alt="Screen Shot 2023-03-01 at 3 34 16 PM" src="https://user-images.githubusercontent.com/46957842/222073780-e11f70e2-d829-4ba8-b949-5ddd1374d2fb.png">

**Comment by olm3ca** [comment]
Excellent news @Heroeshigh - so NVMe is working it seems. That's great. Trackpad is quite bad, but you can enable it with Karabiner app. It works partially that way. Audio will only work with bluetooth.

**Comment by 2697a** [comment]
> 最后我做到了。和@olm3caconfig.plist 并进行了完整的安装。禁止页面是USB接口引起的，左边的接口是USB3.0，我改成右边的USB2.0接口。一切正常，但音乐和视频。 <img alt="屏幕截图 2023-03-01 下午 3 时 33 分 31 分" width="585" src="https://user-images.githubusercontent.com/46957842/222073772-8ef3033c-0052-46b2-871f-66fb566d42c4.png"> <img alt="屏幕截图 2023-03-01 3 34 16 PM" width="868" src="https://user-images.githubusercontent.com/46957842/222073780-e11f70e2-d829-4ba8-b949-5ddd1374d2fb.png">

Great. Can you share your EFI? My configuration is exactly the same as yours. I want to try it. Thank you

**Comment by lucas2023x** [comment]
Big news for nvme users! My configuration is exactly the same as yours too (16gb/512 internal).If you can share the EFI. Thanks!

**Comment by Heroeshigh** [comment]
@2697a @lucas2023xtake it and I've removed the ltlwm and airportltlwm since they are too big, you can add them in, actually there is no
[EFI.zip](https://github.com/olm3ca/PixelbookOSX/files/10860560/EFI.zip)
 need cause they are useless. And most important a full installation is in need, you should make a mac installer medium with the verion you choose. And all of this issue should be over. I'll close it with this post, and if I get some time there could be a note with my installing experience. Just keep in touch.

And honestly thank @olm3ca @meghan06 's support and notes.

**Comment by meghan06** [comment]
Nice job! That's great news.
