### ISSUE TITLE
Solution? - Pixelbook internal SSD 512 with Monterey

### ISSUE THREAD

**Issue by lucas2023x** [olm3ca/PixelbookOSX#21]
I saw a comment about the 512gb ssd not being compatible due to an installation error.

I had the same problem with Mojave due to the version of MrChromebox.

I solved the problem by cloning the partition (for me it only worked by cloning from a virtual machine with the same efi after the first part of the installation that crashed - I used Acronis True Image program)

But maybe it's simpler and maybe cloning from external ssd (eMMC) to internal ssd will work.

If anyone can test. I'm still going to study how to create the efi for monterey so I can test this theory. (if anyone has the pixelbook 512gb internal and this works and can share the efi)

**Comment by meghan06** [comment]
Check out #22, would be cool if you tested this.
