### ISSUE TITLE
About screen brightness

### ISSUE THREAD

**Issue by 2697a** [olm3ca/PixelbookOSX#24]
BetterDisplay can adjust the brightness of the screen. Although there are some problems, it can make the screen less dazzling at night
![161677688377_ pic](https://user-images.githubusercontent.com/24308269/222203222-82e4e2fd-fb69-4eb7-aa42-e658e0523305.jpg)

**Comment by meghan06** [comment]
@olm3ca @2697a Are you both using `BrightnessKeys.kext`? If not, add it. 
Also, try generating a custom `SSDT-PNLF` via SSDTTime, maybe the generic precompiled one doesn't work with the Pixelbook.
Glad to know brightness control has some form of existence now on the Pixelbook, though.

**Comment by olm3ca** [comment]
Yes, using brightnesskeys but doesn't do anything. I've also generated SSDT-PNLF. There's something odd with the display.

**Comment by olm3ca** [comment]
Added this tip to the repo. Thanks, @2697a
