### ISSUE TITLE
May you share the efi files

### ISSUE THREAD

**Issue by gfhdhytghd** [olm3ca/PixelbookOSX#29]

**Comment by gfhdhytghd** [comment]
I would like to know if you are willing to upload the whole efi folder to the repo.
I mate some problems during the installation.

**Comment by gfhdhytghd** [comment]
or，do you provide any remote install services

**Comment by meghan06** [comment]
No, the best way is to create the EFI yourself through trial and error via this guide and Dortania's OpenCore Install Guide.

**Comment by gfhdhytghd** [comment]
Done now
![IMG_2988](https://github.com/olm3ca/PixelbookOSX/assets/102898587/f099584e-bd37-4eac-a454-d7ff8c80ccab)

**Comment by xyx208** [comment]
> Done now ![IMG_2988](https://private-user-images.githubusercontent.com/102898587/299582529-f099584e-bd37-4eac-a454-d7ff8c80ccab.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MjYyNzQsIm5iZiI6MTcyMDUyNTk3NCwicGF0aCI6Ii8xMDI4OTg1ODcvMjk5NTgyNTI5LWYwOTk1ODRlLWJkMzctNGVhYy1hNDU0LWQ3ZmY4YzgwY2NhYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTE1MjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ4M2Q0OTI0MDNkZDI5NTExNDQyZjVhMzUxNDI3ZjQ1ZDQ0YmViNjVjYjhiMWZlY2E3NDRhY2E4Mjc2NGE5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.abU0snGAUlhgaFS2n_19OsFjv7txIWTf8ahk56G7YYI)
大佬，能分享一下你的EFI吗？330219360@@qq.com

**Comment by gfhdhytghd** [comment]
你等过两天的，现在电脑不在身边

**Comment by xyx208** [comment]
> 你等过两天的，现在电脑不在身边

感谢，期待中....

**Comment by gfhdhytghd** [comment]
https://wwz.lanzouq.com/iUEO3242gofe

**Comment by xyx208** [comment]
> https://wwz.lanzouq.com/iUEO3242gofe

谢谢大佬！

**Comment by xyx208** [comment]
> https://wwz.lanzouq.com/iUEO3242gofe
使用你的OC，安装可以进行到剩余12分钟，然后就卡住重启了
我自己配置一个OC，也是同样的问题，大佬能帮看看吗？
`unable to get fs for /system/volumes/data/macos install data`
![IMG_20240710_210144](https://github.com/user-attachments/assets/9db949f9-fc44-4965-83f1-5aca9fc5a442)

![IMG_20240710_210702](https://github.com/user-attachments/assets/82d2da42-6264-4265-9b75-ce6f62e350aa)

**Comment by lucas2023x** [comment]
For me, opencore (OC) by gfhdhytghd worked (Ventura). It gave an error when installing on an empty partition, but it worked when installing over the current Mojave installation. (the system has updated)
The only thing that didn't work was the USB to pendrive (although the mouse and keyboard worked)
(Google Pixelbook Eve I7 7° Gen 16gb Ram 512gb Ssd)

**Comment by gfhdhytghd** [comment]
> > https://wwz.lanzouq.com/iUEO3242gofe
> > 使用你的OC，安装可以进行到最后12分钟，然后就卡住重启了
> > 我自己配置​​的一个OC，也是同样的问题，大佬能帮看看吗？
> > `unable to get fs for /system/volumes/data/macos install data`
> > ![IMG_20240710_210144](https://private-user-images.githubusercontent.com/3462451/350710088-9db949f9-fc44-4965-83f1-5aca9fc5a442.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODkzNjYsIm5iZiI6MTcyMTY4OTA2NiwicGF0aCI6Ii8zNDYyNDUxLzM1MDcxMDA4OC05ZGI5NDlmOS1mYzQ0LTQ5NjUtODNmMS01YWNhOWZjNWE0NDIuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMjI1NzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyODc5ZDA0MGYyOTI0ZjQ4ZjliZTYwMDdjZDg5MDBhOGQwNzM3MDkzYWMxNzAwMDg4NzY0MjM1ZDMzMWQ4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2BQfIzlTk68IsRsooJ46QiKojedjadteNNC52JflgeI)
> 
> ![IMG_20240710_210702](https://private-user-images.githubusercontent.com/3462451/351032346-82d2da42-6264-4265-9b75-ce6f62e350aa.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODkzNjYsIm5iZiI6MTcyMTY4OTA2NiwicGF0aCI6Ii8zNDYyNDUxLzM1MTAzMjM0Ni04MmQyZGE0Mi02MjY0LTQyNjUtOWI3NS1jZTZmNjJlMzUwYWEuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMjI1NzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q2YjMzY2RiYzM5ZTU2ZDA5MTk3ZmNiOGE2NzkyNTEyYTdlMDgyYTJiMzgyMDMxN2Y3ZDFjNmE4YTczNTAxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vQI3OV16EeCxNJweaOqQ80KdHIlCf0gK7Cn4H1uPX4Q)

你好，我是通过磁盘管理软件直接恢复现成的完整APFS的方式进行的安装，所以我并不清楚你的状况是因为什么，我的镜像来自老吴黑苹果

**Comment by xyx208** [comment]
> > > https://wwz.lanzouq.com/iUEO3242gofe
> > > 使用你的OC，安装可以进行到最后12分钟，然后就卡住重启了
> > > 我自己配置​​的一个OC，也是同样的问题，大佬能帮看看吗？
> > > `unable to get fs for /system/volumes/data/macos install data`
> > > ![IMG_20240710_210144](https://private-user-images.githubusercontent.com/3462451/350710088-9db949f9-fc44-4965-83f1-5aca9fc5a442.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODkzNjYsIm5iZiI6MTcyMTY4OTA2NiwicGF0aCI6Ii8zNDYyNDUxLzM1MDcxMDA4OC05ZGI5NDlmOS1mYzQ0LTQ5NjUtODNmMS01YWNhOWZjNWE0NDIuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMjI1NzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyODc5ZDA0MGYyOTI0ZjQ4ZjliZTYwMDdjZDg5MDBhOGQwNzM3MDkzYWMxNzAwMDg4NzY0MjM1ZDMzMWQ4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2BQfIzlTk68IsRsooJ46QiKojedjadteNNC52JflgeI)
> > 
> > 
> > ![IMG_20240710_210702](https://private-user-images.githubusercontent.com/3462451/351032346-82d2da42-6264-4265-9b75-ce6f62e350aa.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2ODkzNjYsIm5iZiI6MTcyMTY4OTA2NiwicGF0aCI6Ii8zNDYyNDUxLzM1MTAzMjM0Ni04MmQyZGE0Mi02MjY0LTQyNjUtOWI3NS1jZTZmNjJlMzUwYWEuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMjI1NzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q2YjMzY2RiYzM5ZTU2ZDA5MTk3ZmNiOGE2NzkyNTEyYTdlMDgyYTJiMzgyMDMxN2Y3ZDFjNmE4YTczNTAxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vQI3OV16EeCxNJweaOqQ80KdHIlCf0gK7Cn4H1uPX4Q)
> 
> 你好，我是通过磁盘管理软件直接恢复现成的完整APFS的方式进行的安装，所以我并不清楚你的状况是因为什么，我的镜像来自老吴黑苹果

感谢你的指导！再次感谢，我去试试。

**Comment by gfhdhytghd** [comment]
太大了发不出，你去老吴黑苹果自己下吧，下os13的

**Comment by xyx208** [comment]
> 太大了发不出，你去老吴黑苹果自己下吧，下os13的

再请教一下，我的BIOS是升到了最新，这个是不是会影响安装黑苹果呀?你降级了吗？

**Comment by gfhdhytghd** [comment]
BIOS没法降级，我的是大约几个月前的版本，理论上是能用的

**Comment by gfhdhytghd** [comment]
理论上最新版本BIOS可以使用

**Comment by zjd1213** [comment]
> > https://wwz.lanzouq.com/iUEO3242gofe
> > 使用你的OC，安装可以进行到最后12分钟，然后就卡住重启了
> > 我自己配置​​的一个OC，也是同样的问题，大佬能帮看看吗？
> > `unable to get fs for /system/volumes/data/macos install data`
> > ![IMG_20240710_210144](https://private-user-images.githubusercontent.com/3462451/350710088-9db949f9-fc44-4965-83f1-5aca9fc5a442.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTYxMTMsIm5iZiI6MTczMDk1NTgxMywicGF0aCI6Ii8zNDYyNDUxLzM1MDcxMDA4OC05ZGI5NDlmOS1mYzQ0LTQ5NjUtODNmMS01YWNhOWZjNWE0NDIuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDUwMzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjQ4MDRmNmI2YTYyOGMzNzJiYzQ1ZjgxZGZhY2ViY2FkMzJiMTJiOWRkOTJmMzEwN2ZmNWI3MzIwYjY3ODY2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ddRsmT1Y14tvzHo0HBsvNEDd0wC1ZhxBFpQ2badZ6Rg)
> 
> ![IMG_20240710_210702](https://private-user-images.githubusercontent.com/3462451/351032346-82d2da42-6264-4265-9b75-ce6f62e350aa.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTYxMTMsIm5iZiI6MTczMDk1NTgxMywicGF0aCI6Ii8zNDYyNDUxLzM1MTAzMjM0Ni04MmQyZGE0Mi02MjY0LTQyNjUtOWI3NS1jZTZmNjJlMzUwYWEuSlBHP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMDUwMzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTUzNjFiYzJjZjA0NWRiYTdlODhiOTc1MjM2ZGQ0OWMyOGFiODI1Y2QwNGI4Y2M1MDJkMDNlNjI3ZWQ2ODA4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.If_WKpsR6RoK0tVVm5igJTe69o0uI9XWt3sK2O7ca74)
你这是2019款的，他们讨论的是2017款，应该需要修改，可以具体搜下，我看有人能装上
