### ISSUE TITLE
Include SSDTs, Kexts, Drivers in the repo?

### ISSUE THREAD

**Issue by patrickjquinn** [olm3ca/PixelbookOSX#3]
Hey! 

Going through the process of getting this up and running with the aim of getting more stuff functional, i've already gone through the processes of de/re compiling the SSDTs directly from the ChromeOS host (i.e on the pixelbook) and tracked down as many useful Kexts as I can that apply to our hardware config.

It would be very useful to have your OpenCore folder (with the kexts and SSDTs you're using) included in this repo for reference as its taking some time recreating your process while extending it with my own using your config as the guide :)

Once i've everything running i'll turn my hand to getting the igpu patches in place to support hardware acceleration. 

I hope you dont mind sharing!

**Comment by olm3ca** [comment]
Yes of course - adding to the main Readme now. Thanks for any ideas you have!

**Comment by olm3ca** [comment]
https://www.dropbox.com/s/vml6tl25rvhuks1/efi4.zip?dl=0

**Comment by olm3ca** [comment]
One thing to note: the current setting in config.plist for what should be the correct AAPL,ig-platform-id of 00001E59 will hang. If you change it to an invalid ID like 16590000 it will boot with no acceleration.

**Comment by patrickjquinn** [comment]
Good to know! I'll look into that :)

**Comment by olm3ca** [comment]
I'm wondering if you could share the SSDTs you've built? I'm realizing now that the prebuilt ones I got from opencore tutorial are not correct. I'm running into an error on Linux and Windows in trying to generate my own via SSDT Time. If you wouldn't mind sharing the ones you've already built that would help with some testing I'm doing. Thanks!

**Comment by patrickjquinn** [comment]
Here are the two patched SSDTs and my dumped DSDT https://drive.google.com/file/d/1B_4sgXejFkrrbsgdy6rQHMT-DKoaip8l/view?usp=sharing i'm using the universal ones for everything else (PLUG, XOSI, USBX).

To generate them I used crouton (rather than crostini as thats a VM rather than a chroot environment) on ChromeOS itself. I'm flashing the UEFI firmware now so i'm about to lose access to that sadly and will have to jump to native Linux if I need any further ones.

**Comment by olm3ca** [comment]
Meant to reply earlier: thanks for that. We're discussing on the chrultrabook discord server in #hackintosh if you're interested. A question right now is if the MEI is actually being identified by Mac OS / Linux. Apparently MrChromebox's firmware might need to enable it, otherwise graphics acceleration won't be possible. This is one idea. Let me know how your progress is going - thanks!

**Comment by patrickjquinn** [comment]
I’ll jump into discord shortly! Interesting on the firmware side of things, surprised it has to be at that level! 

Unfortunately I’ve been unable to get the installer to boot (I think this goes back to the graphics actually) but plan on spending some portion of Christmas Eve digging into all the issues I’m seeing during the boot process 🙂

**Comment by patrickjquinn** [comment]
Right, have a successful build of it running on the internal NVME, just going through the motions getting stuff debugged now 👍 Couldn't find the hackintosh discord you where mentioning? Would you mind linking it here?

Also as with Windows and other Alt OS, you've obviously downgraded the firmware for the trackback using the firmware util script yeah?

**Comment by olm3ca** [comment]
Hey, try this for Discord: https://discord.gg/hE2aR9WH - there's also a link to it on the chrultrabook subreddit if that doesn't work. That's great you've got it working! Just in case, I'm uploading the latest EFI to the readme on this repo. I built a usb map that is working well (for my use case) and also have some good SSDTs in place. In case this helps you: https://www.dropbox.com/s/w1oh0do8k0b8d8o/EFI5.zip?dl=0

I did downgrade the trackpad firmware, yes. It's still not working for me though. What do you have working? Any progress with the HD615 acceleration?

**Comment by patrickjquinn** [comment]
I'll join that now thanks! 

I've added my SSDTs in, modified a few portions of the plist based on the kaby lake guidelines and have changed the model over to a MacbookPro14,2 which seems to get rid of the unsupported CPU error in the boot log. Messing around with the framebuffer to see if its just a case of further igpu patching needed, so far no dice. Also tried the NUC igpu device ID which was suggested but again, no joy. Will keep digging! 

Also removed the conflicting VoodooHDA from the plist. Trying to get power management working now also.

Looking at the linux HIDI2c driver for the touchpad to see if any kexts are similar and can be used as the basis of a driver.

**Comment by patrickjquinn** [comment]
Will try out your new EFI now 👍

**Comment by olm3ca** [comment]
That's a good tip re: 14,2. I've been seeing that same error, will make that change. I've tried every one of the platform-ids for this chip, as well as many framebuffer args. It's being quite stubborn. 

VoodooHDA is definitely out for me too. AppleALC seems to be the way to go but will need some work. If you get specific things working (trackpad, sound, etc), I'd always appreciate knowing!

**Comment by olm3ca** [comment]
Hey - for audio, I found something. On Windows the codecs are Google MAX98927 & Realtek 5514 / 5663. I just spotted this on Torvalds' repo: https://github.com/torvalds/linux/blob/master/sound/soc/intel/boards/kbl_rt5663_rt5514_max98927.c

Looks recent, thought it might be useful.
