### ISSUE TITLE
Unable to install to emmc due to a lack of support in mac os.

### ISSUE THREAD

**Issue by Shaddow798** [olm3ca/PixelbookOSX#4]
Since apple doesn't have a mac with a emmc flash chip and likely never will there is no support to boot of emmc.

But it should be possible to create some kind of janky emmc drive with the base of a sd card driver.

It would be nice to look into but i have a i7 not a i5

**Comment by olm3ca** [comment]
Sadly I have zero knowledge on how to do this. I have an external Samsung SSD and it works fine but isn't exactly portable.
