### ISSUE TITLE
UEFI mojave installer not available

### ISSUE THREAD

**Issue by Tpow99** [olm3ca/PixelbookOSX#7]
Hello, I have been working on and enjoying using your method to get MAC OS onto the pixelbook. I have run into an issue with the boot device. When I go into the UEFI startup, I attempt to boot from the USB, which returns failed to boot. I believe this is because the MAC install media is a separate partition. However, when I go to boot from file, only the EFI partition is an available option. My install media is mapped as below:
PNY USB
        - Mojave installer media
                - mojave installer
       -EFI
                - BOOT
                - OC

I am not sure what I can do to get the Mojave installer partition to show up as a viable option. Any help or explanation is appreciated, thank you!

**Comment by Tpow99** [comment]
I apologize, the indentation got messed up on post:
PNY has children Mojave installer media and EFI
Mojave installer media has child mojave installer
EFI has children BOOT and OC

**Comment by olm3ca** [comment]
I'm not exactly following. You should have two drives: one is the installer, one is the target drive where Mojave will be installed. Is your PNY USB a Mojave installer? Did you mount the EFI partition on that drive and copy the contents of what I shared? There are only two partitions on the install USB - the Mojave install and then EFI. 

On the second, target drive, you install Mojave and will also need to set up EFI, but that can wait. You should be able to boot when you have a working EFI on the USB.

If you need more help, join us on Discord in #hackintosh, here: https://discord.gg/MMBqdp82

**Comment by olm3ca** [comment]
one more question, you're sure you formatted the PNY drive as GUID, right? If it's MBR (which is standard, most USBs come formatted as FAT32 with Master Boot Record instead of GUID)... it won't boot 

* Edit - I just added this to the instructions as it's important and I may not have made that clear.

**Comment by Tpow99** [comment]
The PNY is my usb installer, I used a mac and the createInstallMedia command to create it then added the EFI as the second partition on that USB. I am going to check right now that I have it set as a GUID and recreate the install media, I will get back to you on that part. 

Edit - I checked and it is a GUID partition format, the problem I am mainly having is that when I choose boot menu > PNY USB it fails and when I choose boot from file > only the EFI partition is showing as a device to choose the installer file from. Does this likely mean the USB is formatted incorrect?

**Comment by olm3ca** [comment]
You didn't create the EFI partition, right? When you have GUID partition layout, EFI is already part of the partition map. It's a small, 100-200mb partition. You should use the MountEFI tool to mount the existing EFI partition and copy the files there.

**Comment by Tpow99** [comment]
Correct, I placed the boot and OC folders directly into the EFI partition.

**Comment by olm3ca** [comment]
That's odd, then. You might want to create the Mojave installer again from the beginning and make sure it boots correctly on your Mac first. Then mount EFI, copy the files I linked (try re-downloading again perhaps) and it should boot when selected.

**Comment by Tpow99** [comment]
upon recleaning and mounting the installer, I noticed this time that the device name changed to Mojave installer and not just the volume name.  I think i changed a setting on my mac to change the way the volumes and devices were viewed. I think it may be important the device is made the installer instead of just the volume on the device. I am adding the files of a fresh download to the EFI partition right now and then will attempt to boot from the installer this time. 

Unfortunately, this still was not successful at botting.

**Comment by Tpow99** [comment]
https://drive.google.com/drive/folders/1pBSz5ZNxiqsbjLmZqz_ZU6kDXYJF091a?usp=sharing
Here is a link with images of my boot device.

**Comment by Tpow99** [comment]
Out of curiosity is there anything that would limit the EFI you have created specifically to a certain Mojave build? OR would any Mojave build work?

Edit - I am in class and have not tried this yet, but I just realized when extracting the folder on my windows machine that there ar e two folders in your EFI creation, I believe I have been using the regular EFI folder in the zip and not the EFI in the macos portion of the file.

**Comment by olm3ca** [comment]
Your images helped a lot. The EFI partition must start first with an EFI folder, followed by OC and Boot folders. This is why it's not recognizing the drive as bootable. See here: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/opencore-efi.html

**Comment by Tpow99** [comment]
You were absolutely correct! Started right up.
