### ISSUE TITLE
How are the performance for Final Cut and Logic Pro?

### ISSUE THREAD

**Issue by guglielmobartelloni** [olm3ca/PixelbookOSX#8]
And I just wanted to say that you are a legend man for making this possible

**Comment by olm3ca** [comment]
Hey, thanks for checking this project out. It's been fun. So Final Cut Pro works really well, check out my video post here: https://www.reddit.com/r/PixelBook/comments/kvmvkj/final_cut_pro_x_video_editing_on_the_pixelbook/

Your one limitation is that you need to find a 10.4.9 installer (I grabbed one online) as the latest FCPX won't install unless you're on Catalina or Big Sur. 

I didn't test Logic Pro.
