### ISSUE TITLE
Trackpad is not always detected

### ISSUE THREAD

**Issue by craigbeat** [olm3ca/PixelbookOSX#9]
In Karabiner, the Trackpad device is not always detected.

**Notes:**

- For the most part, I thought it was never being detected, but on one occasion, I managed to get it to work. The only thing I did different to when I normally boot is reset NVRAM. On subsequent boots, trackpad was not detected
- I am using the downgraded firmware, as I also use Windows
- I have an i5 device
- Touchscreen works fine

**Comment by olm3ca** [comment]
I wish I could help with this one. My trackpad died - it no longer responds at all. When it worked a month or two ago, I was able to use it somewhat but the performance was very poor. There should be a better way to get it to work.
